# -*- coding: utf-8 -*-
"""Nattapong Panthiya - DataMiningLab_02_Decision Tree Classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CvA97pJthcALVL7a_TkA21K8We_d7K_8

# Decision Tree Classification

## จุดประสงค์



*   เรียนรู้การจำแนกด้วยต้นไม้ตัดสินใจ (Decision Tree Classification) และหลักการเลือกแอตทริบิวต์ในการสร้างต้นไม้ตัดสินใจ (attribute selection measures)
*   การสร้างตัวจำแนกต้นไม้ตัดสินใจ (Decision Tree Classifier) ด้วย Python Scikit-learn package

## Decision Tree Classifier Building in Scikit-learn

### import ไลบราลีที่เกี่ยวข้อง
ก่อนอื่นให้โหลดไลบรารีที่จำเป็นเข้ามาใน notebook ของเราก่อน ด้วยคำสั่ง import ดังต่อไปนี้
"""

# Load libraries
import pandas as pd
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
from sklearn.model_selection import train_test_split # Import train_test_split function
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation

"""### Loading Data

ชุดข้อมูลที่จะใช้ใน Lab นี้ คือ  Pima Indian Diabetes โดยเราจะนำเข้าด้วยฟังก์ชัน read_csv() ที่อยู่ในไลบรารี pandas  คุณสามารถดาวน์โหลดข้อมูลได้[ที่นี่](https://www.kaggle.com/datasets/uciml/pima-indians-diabetes-database)
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("uciml/pima-indians-diabetes-database")

print("Path to dataset files:", path)

from google.colab import files
uploaded = files.upload()

col_names = ['pregnant', 'glucose', 'bp', 'skin', 'insulin', 'bmi', 'pedigree', 'age', 'label']
# load dataset
pima = pd.read_csv(path+"/diabetes.csv", header=0, names=col_names)
pima

"""### กำหนด Dependent variable (Class) และ Independent variables

ในขั้นตอนนี้ให้แบ่งคอลัมน์ในชุดข้อมูลออกเป็นสองประเภท คือ
*  ตัวแปรตาม (Dependent variable, Target variable, แอตทริบิวต์ที่บอก class)
*  ตัวแปรอิสระ (Independent variables, Features, แอตทริบิวต์ที่ช่วยในการจำแนก)

โดยให้ตัวแปรอิสระเก็บไว้ใน List X ส่วนตัวแปรตามให้เก็บไว้ใน List y

"""

#split dataset in features and target variable
feature_cols = ['pregnant', 'insulin', 'bmi', 'age','glucose','bp','pedigree']
X = pima[feature_cols] # Features
y = pima.label # Target variable
print(X)
print(y)

"""### Splitting Data

เพื่อการประเมินประสิทธิภาพของโมเดลภายหลังจากที่สร้างโมเดลเสร็จแล้ว เราต้องแบ่งชุดข้อมูลออกเป็นชุดฝึกหัด (Training set) และชุดทดสอบ (Test set) โดยใช้ฟังก์ชัน train_test_split() ซึ่งการเรียกใช้ฟังก์ชันนี้ ต้องมีการส่งค่าให้พารามิเตอร์ 3 ตัว คือ features, target และ test_set size
"""

# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1) # 70% training and 30% test
print(X_train)
print(y_train)
print(X_test)

"""### Building Decision Tree Model
มาสร้าง Decision Tree Model โดยใช้ Scikit-learn กัน
ประกอบด้วยขั้นตอน ดังนี้


1.   สร้างออปเจ็ก Decision Tree Classifier ด้วยฟังก์ชัน DecisionTreeClassifier()


```
object_name = DecisionTreeClassifier()
```



2.   สร้างต้นไม้ตัดสินใจจากชุดข้อมูลฝึกหัด (Training set) ด้วยการนำออปเจ็กตัวจำแนกจากขั้นตอนที่ 1 มาเรียกใช้เมธอด fit() โดยส่งค่าของตัวแปรอิสระของชุดผึกหัด (features) และตัวแปรตาม (target) ของชุดฝึกหัดเข้าไปทำงานในเมธอด


```
obj_name = obj_name.fit(train_features,train_target)
```


3.   นำชุดทดสอบ (Test set) มาทดลองให้โมเดลทำการจำแนก ด้วยการนำออปเจ็กตัวจำแนกมากเรียกใช้เมธอด predict() โดยส่งค่าตัวแปรอิสระของชุดทดสอบเข้าไปทำงานในเมธอด



```
variable_name = obj_name.predict(test_features)
```




"""

# Create Decision Tree classifer object
clf = DecisionTreeClassifier()

# Train Decision Tree Classifer
clf = clf.fit(X_train,y_train)

#Predict the response for test dataset
y_pred = clf.predict(X_test)
print(y_pred)
print(len(y_pred))

"""### Evaluating Model
การประเมินประสิทธิภาพของโมเดลการจำแนก เป็นการประเมินว่าโมเดลสามารถจำแนกประเภทของวัตถุข้อมูลที่ไม่เคยเห็นมาก่อนได้ดีมากน้อยแค่ไหน โดยการเปรียบเทียบค่าจริง (เฉลย)ในชุดการทดสอบกับค่าที่โมเดลคาดการณ์ จากนั้นนำมาคำนวณค่าตัวชี้วัดในการประเมินประสิทธิภาพต่าง ๆ เช่น Accuracy
"""

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

"""### Visualizing Decision Trees
เราสามารถใช้ฟังก์ชัน export_graphviz ของ Scikit-learn เพื่อแสดงแผนภาพต้นไม้ (Tree chart) ใน Colab notebook สำหรับการลงจุดต้นไม้ ซึ่งต้องติดตั้งแพ็กเกจชื่อว่า  graphviz และ pydotplus ด้วย

```
!pip install -q graphviz

!pip install -q pydotplus
```



ฟังก์ชัน export_graphviz แปลงตัวจำแนกต้นไม้ตัดสินใจให้เป็น dot file และ pydotplus แปลง dot file นี้ให้เป็น png หรือรูปแบบที่สามารถแสดงผลได้บน Colab notebook
"""

!pip install -q graphviz
!pip install -q pydotplus

from sklearn.tree import export_graphviz
#from sklearn.externals.six import StringIO
from six import StringIO
from IPython.display import Image
import pydotplus

dot_data = StringIO()
export_graphviz(clf, out_file=dot_data,
                filled=True, rounded=True,
                special_characters=True,feature_names = feature_cols,class_names=['0','1'])
graph = pydotplus.graph_from_dot_data(dot_data.getvalue())
graph.write_png('diabetes.png')
Image(graph.create_png())

"""จากแผนภาพต้นไม้การตัดสินใจ แต่ละโหนดจะมีกฎการตัดสินใจที่ใช้ในการแบ่งวัตถุข้อมูลในชุดข้อมูลออกเป็นกลุ่มย่อย และอัตราส่วน Gini (Gini ratio) ที่ใช้วัดความไม่บริสุทธิ์ (สิ่งเจือปน) ของโหนด (โหนดบริสุทธิ์เมื่อวัตถุข้อมูลทั้งหมดอยู่ในคลาสเดียวกัน คือ มีค่า Gini ratio เป็น 0 โหนดดังกล่าวเรียกว่าโหนดใบ (Leaf node))

สังเกตได้ว่า ต้นไม้ติดสินใจตามภาพด้านบนเป็นต้นไม้ที่ยังไม่ได้มีการตัดแต่งกิ่ง (unpruned) ในบางครั้ง เราสามารถเพิ่มประสิทธิภาพของตัวจำแนกแบบต้นไม้ตัดสินใจได้ด้วยการตัดแต่งกิ่งของต้นไม้ (tree pruning)

### Optimizing Decision Tree Performance
ใน Scikit-learn การเพิ่มประสิทธิภาพของตัวจําแนกต้นไม้ตัดสินใจสามารถทำได้โดยการตัดแต่งกิ่งแบบล่วงหน้า (pre-pruning) เท่านั้น โดยเราสามารถกำหนดค่าความลึกสูงสุดของต้นไม้ (Maximum depth of the tree) เพื่อใช้เป็นตัวแปรควบคุมการตัดแต่งกิ่งแบบล่วงหน้า

ตัวอย่างต่อไปนี้ คุณสามารถสร้างตัวจำแนกแบบต้นไม้ตัดสินใจด้วยฟังก์ชัน DecisionTreeClassifier() โดยใช้ชุดข้อมูลชุดเดิม แต่กำหนดค่าพารามิเตอร์ max_depth = 3 นอกจากนี้ เรายังสามารถลองเปลี่ยนวิธีการเลือกแอตทริบิวต์ในการตัดสินใจวิธีอื่นที่ไม่ใช่การใช้ค่า Gini index เช่น ใช้ค่าเอนโทรปี (entropy) ในการเลือกแอตทริบิวต์ในการตัดสินใจแทน



*   criterion : optional (default=”gini”) or Choose attribute selection measure: This parameter allows us to use the different-different attribute selection measure. Supported criteria are “gini” for the Gini index and “entropy” for the information gain.

*   splitter : string, optional (default=”best”) or Split Strategy: This parameter allows us to choose the split strategy. Supported strategies are “best” to choose the best split and “random” to choose the best random split.

*   max_depth : int or None, optional (default=None) or Maximum Depth of a Tree: The maximum depth of the tree. If None, then nodes are expanded until all the leaves contain less than min_samples_split samples. The higher value of maximum depth causes overfitting, and a lower value causes underfitting (Source).
"""

# Create Decision Tree classifer object
clf = DecisionTreeClassifier(criterion="entropy", max_depth=3)

# Train Decision Tree Classifer
clf = clf.fit(X_train,y_train)

#Predict the response for test dataset
y_pred = clf.predict(X_test)

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

"""จะเห็นว่า ตัวจำแนกแบบต้นไม้ตัดสินใจตัวใหม่ทีมีการตัดแต่งกิ่งและเปลี่ยนวิธีการเลือกแอตทริบิวต์ในการตัดสินใจ ทำให้ค่า Accuracy เพิ่มขึ้น

### Visualizing Decision Trees

ลองแสดงแผนภาพต้นไม้ตัดสินใจตัวใหม่
"""

from six import StringIO
from IPython.display import Image
from sklearn.tree import export_graphviz
import pydotplus
dot_data = StringIO()
export_graphviz(clf, out_file=dot_data,
                filled=True, rounded=True,
                special_characters=True, feature_names = feature_cols,class_names=['0','1'])
graph = pydotplus.graph_from_dot_data(dot_data.getvalue())
graph.write_png('diabetes.png')
Image(graph.create_png())

"""# แบบฝึกหัด Lab2

ให้สร้างตัวจำแนกแบบต้นไม้ตัดสินใจ ประเมินประสิทธิภาพของตัวจำแนกโดยการหาค่า Accuracy และแสดงแผนภาพต้นไม้ตัดสินใจ โดยใช้ชุดข้อมูล Iris.csv

โดยนักศึกษาสามารถดาวน์โหลดชุดข้อมูลได้[ที่นี่](https://www.kaggle.com/datasets/saurabh00007/iriscsv)

"""

path = kagglehub.dataset_download("saurabh00007/iriscsv")
print("Path to dataset files:", path)

col_names = ['SepalLengthCm','SepalWidthCm','PetalLengthCm','PetalWidthCm','Species']
pima = pd.read_csv(path + "/Iris.csv", header=0, names=col_names)
pima

feature_cols = ['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']

x_data = pima[feature_cols] # Features
y_data = pima.Species # Target variable
print(x_data)
print(y_data)

# Split dataset into training set and test set
Xx_train, Xx_test, Yy_train, Yy_test = train_test_split(x_data, y_data, test_size=0.3, random_state=1) # 70% training and 30% test
print(Xx_train)
print(Yy_train)
print(Xx_test)

# Create Decision Tree classifer object
Iris_clf = DecisionTreeClassifier()

# Train Decision Tree Classifer
Iris_clf = clf.fit(Xx_train,Yy_train)

#Predict the response for test dataset
Yy_pred = clf.predict(Xx_test)
print(y_pred)
print(len(Yy_pred))

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(Yy_test, Yy_pred))

from six import StringIO
from IPython.display import Image
from sklearn.tree import export_graphviz
import pydotplus
dot_data = StringIO()
export_graphviz(clf, out_file=dot_data,
                filled=True, rounded=True,
                special_characters=True, feature_names = feature_cols,class_names=['Iris-setosa','Iris-virginica','Iris-versicolor'])
graph = pydotplus.graph_from_dot_data(dot_data.getvalue())
graph.write_png('Iris_diabetes.png')
Image(graph.create_png())