# -*- coding: utf-8 -*-
"""Nattapong Panthiya - DataMiningLab_05_Hierarchical Clustering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13DbHYCyJLj27QBqi_KdDonDpIZwJek0k

# Hierarchical Clustering

การจัดกลุ่มแบบลำดับชั้น (Hierarchical Clustering) เป็นวิธีการเรียนรู้แบบไม่มีผู้สอน (Unsupervised Learning) ที่ใช้ในการจัดกลุ่มจุดข้อมูล โดยอัลกอริทึมจะสร้างคลัสเตอร์จากการวัดความแตกต่าง (dissimilarity)  ระหว่างข้อมูล จุดข้อมูลที่มีความแตกต่างกันน้อยจะถูกจัดให้อยู่ในคลัสเตอร์เดียวกัน

วิธีนี้ใช้กับข้อมูลใดก็ได้เพื่อให้เห็นภาพ (visualize) และตีความ (interpret) ความสัมพันธ์ระหว่างจุดข้อมูลแต่ละจุด

## Agglomerative Clustering

เป็นวิธีการจัดกลุ่มแบบลำดับชั้นประเภทหนึ่ง ที่ใช้วิธีสร้างกลุ่มจากล่างขึ้นบน (buttom up approach) โดยเริ่มต้นด้วยการที่แต่ละจุดข้อมูลแยกเป็นคลัสเตอร์ของตนเอง จากนั้น จะทำการรวมรวมคลัสเตอร์ที่มีระยะห่างระหว่างกันสั้นที่สุดเข้าด้วยกันเพื่อสร้างคลัสเตอร์ที่ใหญ่ขึ้น และทำขั้นตอนการรวมคลัสเตอร์นี้ทำซ้ำจนกระทั่งได้คลัสเตอร์ขนาดใหญ่เพียงคลัสเตอร์เดียวที่มีจุดข้อมูลทั้งหมดเป็นสมาชิก

สิ่งที่ต้องพิจารณาในการการจัดกลุ่มแบบลำดับชั้น คือ

*   วิธีการวัดระยะทาง (distance measure)
*   วิธีการเชื่อมโยง (linkage measure)

ซึ่งใน Lab นี้ เราจะใช้การวัดระยะทางแบบยุคลิด (Euclidean distance)และวิธีการเชื่อมโยงของ Ward

## Example

เราจะทำการจัดกลุ่มจุดข้อมูลจำนวน 10 จุด ที่ประกอบไปด้วยแอตทริบิวต์ x และ y ดังตาราง

| point 	| x  	| y  	|
|-------|----|----|
| p1    	| 4  	| 21 	|
| p2    	| 5  	| 19 	|
| p3    	| 10 	| 24 	|
| p4    	| 4  	| 17 	|
| p5    	| 3  	| 16 	|
| p6    	| 11 	| 25 	|
| p7    	| 14 	| 24 	|
| p8    	| 6  	| 22 	|
| p9    	| 10 	| 21 	|
| p10   	| 12 	| 21 	|

เริ่มด้วยการลอง plot จุดข้อมูลเพื่อให้เห็นภาพก่อน โดยการเรียกใช้ scatter() ใน matplotlib
"""

import numpy as np
import matplotlib.pyplot as plt

x = [4, 5, 10, 4, 3, 11, 14 , 6, 10, 12]
y = [21, 19, 24, 17, 16, 25, 24, 22, 21, 21]

plt.scatter(x, y)
plt.show()

"""จากนั้นเราจะทำการคำนวณการเชื่อมโยงแบบ Ward โดยใช้ระยะทางแบบยุคลิด และแสดงภาพโดยใช้เดนโดรแกรม (Dendrogram)

ซึ่งต้อง import ไลบรารีดังนี้


```
from scipy.cluster.hierarchy import dendrogram, linkage
```




"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.cluster.hierarchy import dendrogram, linkage

x = [4, 5, 10, 4, 3, 11, 14 , 6, 10, 12]
y = [21, 19, 24, 17, 16, 25, 24, 22, 21, 21]

data = list(zip(x, y))

linkage_data = linkage(data, method='ward', metric='euclidean')
dendrogram(linkage_data)

plt.show()

"""จากนั้น เราลองใช้ไลบรารี scikit-learn ของ Python จัดกลุ่มข้อมูลด้วยวิธีการ Agglomerative Clustering

ซึ่งต้องทำการ import ไลบรารี ดังต่อไปนี้



```
from sklearn.cluster import AgglomerativeClustering
```


แล้วทำการแสดงผลลัพธ์ของการจัดกลุ่ม บนแกน 2 มิติ
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import AgglomerativeClustering

x = [4, 5, 10, 4, 3, 11, 14 , 6, 10, 12]
y = [21, 19, 24, 17, 16, 25, 24, 22, 21, 21]

data = list(zip(x, y))

hierarchical_cluster = AgglomerativeClustering(n_clusters=3, metric='euclidean', linkage='ward')
labels = hierarchical_cluster.fit_predict(data)
print(labels)

plt.scatter(x, y, c=labels)
plt.show()

"""# แบบฝึกหัด

ให้ลองจัดกลุ่มข้อมูลต่อไปนี้ ด้วยวิธี Agglomerative Clusteringที่ใช้การวัดระยะทางแบบยุคลิด (Euclidean distance)และวิธีการเชื่อมโยงของ Ward โดยให้แสดง
1. Dendrogram
2. ผลลัพธ์เป็น 3 คลัสเตอร์บนแกน 2 มิติ

| point 	| x  	| y  	|
|-------|----|----|
| p1    	| 4  	| 21 	|
| p2    	| 5  	| 19 	|
| p3    	| 10 	| 24 	|
| p4    	| 4  	| 17 	|
| p5    	| 9  	| 13 	|
| p6    	| 11 	| 15 	|
| p7    	| 14 	| 24 	|
| p8    	| 6  	| 22 	|
| p9    	| 10 	| 21 	|
| p10   	| 12 	| 21 	|
| p11    	| 8 	| 14 	|
| p12    	| 3 	| 16 	|
| p13    	| 11	| 25 	|
| p14    	| 10 	| 15 	|
| p15   	| 9 	| 10 	|
"""

# ให้เขียน code ของแบบฝึกหัดที่นี่
cx = [4, 5, 10, 4, 9, 11, 14, 6, 10, 12, 8, 3, 11, 10, 9]
cy = [21, 19, 24, 17, 13, 15, 24, 22, 21, 21, 14, 16, 25, 15, 10 ]

plt.scatter(cx, cy)
plt.show()
print()

data = list(zip(cx, cy))

linkage_data = linkage(data, method='ward', metric='euclidean')
dendrogram(linkage_data)

plt.show()
print()

data = list(zip(cx, cy))

hierarchical_cluster = AgglomerativeClustering(n_clusters=3, metric='euclidean', linkage='ward')
labels = hierarchical_cluster.fit_predict(data)
print(labels)

plt.scatter(x, y, c=labels)
plt.show()