# -*- coding: utf-8 -*-
"""Nattapong Panthiya - DataMiningLab_01_Similarity_Measures.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xpn-jpLFzDGP_EYB8f85wcdC82vwk3Up

# Similarity Measures
การวัดความคล้ายคลึงกันคือการวัดว่าวัตถุข้อมูลสองชิ้นมีความเหมือนกันมากน้อยเพียงใด

การวัดความคล้ายคลึงในบริบทของการทำเหมืองข้อมูลหรือการเรียนรู้ของเครื่อง คือ การหาระยะทาง (distance) ของคู่วัตถุข้อมูลในหลายมิติ (จำนวนมิติ คือ จำนวนแอตทริบิวต์ของวัตถุข้อมูล) หากระยะทางห่างน้อย แสดงว่าวัตถุข้อมูลคู่นั้นมีความคล้ายคลึงกันในระดับสูง ในขณะที่ถ้าระยะทางห่างกันมากคู่วัตถุข้อมูลนั้นก็จะมีความคล้ายคลึงกันในระดับต่ำ

# Euclidean Distance

ระยะทางแบบยุคลิดเป็นการวัดระยะทางที่ใช้บ่อยที่สุด ในกรณีส่วนใหญ่เมื่อพูดถึงระยะทางก็มักจะหมายถึงระยะทางแบบยุคลิด เป็นวิธีการหาระยะทางที่เหมาะกับวัตถุข้อมูลที่มีจำนวนมิติมาก ๆ และค่าในแต่ละมิติเป็น continuous data

**สูตร**

$d(p,q) = \sqrt{\sum_{i=1}^n {(p_i-q_i)}^2}$
"""

from math import*
def euclidean_distance(p,q):
  return sqrt(sum(pow(a-b,2) for a, b in zip(p, q)))

print(round(euclidean_distance([0,0,0],[5,-2,7]),4))

"""**แบบฝึกหัด 1.1** ให้หาระยะทางแบบยูคลิดของทุกคู่ของจุดในตารางด้านล่าง

| point 	| x 	| y 	|
|-------	|---	|---	|
| p1    	| 0 	| 2 	|
| p2    	| 2 	| 0 	|
| p3    	| 3 	| 1 	|
| p4    	| 5 	| 1 	|
"""

from math import*
def euclidean_distance(p,q):
  return sqrt(sum(pow(a-b,2) for a, b in zip(p, q)))

# แสดงค่า d(p1,p2)
print('L2(p1,p2) = ',round(euclidean_distance([0,2],[2,0]),3))

# แสดงค่า d(p1,p3)
print('L2(p1,p3) = ',round(euclidean_distance([0,2],[3,1]),3))

# แสดงค่า d(p1,p4)
print('L2(p1,p4) = ',round(euclidean_distance([0,2],[5,1]),3))

# แสดงค่า d(p2,p3)
print('L2(p2,p3) = ',round(euclidean_distance([2,0],[3,1]),3))

# แสดงค่า d(p2,p4)
print('L2(p2,p4) = ',round(euclidean_distance([2,0],[5,1]),3))

# แสดงค่า d(p3,p4)
print('L2(p3,p4) = ',round(euclidean_distance([3,1],[5,1]),3))

"""# Manhattan distance ($L_1 norm$)

ระยะทางแมนฮัตตันเป็นระยะทางระหว่างจุดสองจุดที่คำนวณจากผลรวมของความแตกต่างสัมบูรณ์ของพิกัดคาร์ทีเซียน พูดง่ายๆ ว่าเป็นผลรวมของผลต่างระหว่างพิกัด x และพิกัด y (ในกรณี 2 มิติ) นั่นเอง

**สูตร**

$L_1 norm(p,q) = \sum_{i=1}^n |{p_i-q_i}|$

**แบบฝึกหัด 1.2** ให้สร้างฟังก์ชันในการหาระยะทางแบบ $L_1 norm$
"""

from math import*
def l1_norm(p,q):
  # การหาค่าสัมบูรณ์สามารถเรียกใช้ฟังก์ชัน abs() ได้
  return sum(abs(a-b) for a, b in zip(p, q))

"""**แบบฝึกหัด 1.3** ให้หา Manhattan distance ($L_1norm$) ของทุกคู่ของจุดในตารางด้านล่าง

| point 	| x 	| y 	|
|-------	|---	|---	|
| p1    	| 0 	| 2 	|
| p2    	| 2 	| 0 	|
| p3    	| 3 	| 1 	|
| p4    	| 5 	| 1 	|
"""

# แสดงค่า L1_norm(p1,p2)
print('L1(p1,p2) = ', l1_norm([0,2],[2,0]))

# แสดงค่า L1_norm(p1,p3)
print('L1(p1,p3) = ', l1_norm([0,2],[3,1]))

# แสดงค่า L1_norm(p1,p4)
print('L1(p1,p4) = ', l1_norm([0,2],[5,1]))

# แสดงค่า L1_norm(p2,p3)
print('L1(p2,p3) = ', l1_norm([2,0],[3,1]))

# แสดงค่า L1_norm(p2,p4)
print('L1(p2,p4) = ', l1_norm([2,0],[5,1]))

# แสดงค่า L1_norm(p3,p4)
print('L1(p3,p4) = ', l1_norm([3,1],[5,1]))

"""L_Max"""

#L_Max
def l_max(p, q):
  return max(abs(a -b) for a,b in zip( p, q ))

print('L1(p1,p2) = ', l_max([0,2],[2,0]))

# แสดงค่า L_Max(p1,p3)
print('L1(p1,p3) = ', l_max([0,2],[3,1]))

# แสดงค่า L_Max(p1,p4)
print('L1(p1,p4) = ', l_max([0,2],[5,1]))

# แสดงค่า L_Max(p2,p3)
print('L1(p2,p3) = ', l_max([2,0],[3,1]))

# แสดงค่า L_Max(p2,p4)
print('L1(p2,p4) = ', l_max([2,0],[5,1]))

# แสดงค่า L_Max(p3,p4)
print('L1(p3,p4) = ', l_max([3,1],[5,1]))