# -*- coding: utf-8 -*-
"""Nattapong Panthiya - Lab_Dimensionality Reduction: PCA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TjrX-FYhq4J_JjT7hLzT3hjk3uJ37MvO

# การวิเคราะห์องค์ประกอบหลัก (Principal Component Analysis: PCA)

เป็นเทคนิคทางสถิติที่ใช้ในการวิเคราะห์ข้อมูลหลายตัวแปร เพื่อค้นหาความสัมพันธ์ระหว่างตัวแปรต่าง ๆ และค้นหาองค์ประกอบหลัก (principal components) ของข้อมูล ส่งผลให้เกิดการลดขนาดของเมทริกซ์  ซึ่งการอธิบายข้อมูลจะทำได้ง่ายขึ้นเพราะข้อมูลมีความซับซ้อนลดลง นอกจากนี้ยังช่วยลดขนาดของคุณลักษณะ (Features) ซึ่งทำให้การสร้างโมเดลใช้เวลาน้อยลงด้วย

PCA จะทำการสร้างตัวแปรที่เรียกว่า component โดยแต่ละ component จะไม่มีความสัมพันธ์กัน component ตัวแรกจะมีค่า variance สูงที่สุด ซึ่งจะอธิบายข้อมูลได้มากที่สุด และตัวถัดไปก็จะมี variance ลดลงตามลำดับ โดยจำนวน component ที่เหมาะสมที่ถูกเลือกมาใช้ควรจะครอบคลุม variance ประมาณ 80–90%

![](https://drive.google.com/uc?export=view&id=1-RldiBehyRjmEQ36AWzmYdfUyKe7QnL0)

ที่มาภาพ: Learn About Principal Component Analysis in Details!
Shilash M — Published On March 22, 2022
https://www.analyticsvidhya.com/blog/2022/03/learn-about-principal-component-analysis-in-details/

## ขั้นตอนสำคัญของ PCA:


* การทำ standardization: เป็นการปรับขนาดของข้อมูลให้มีค่า mean เท่ากับ 0 และส่วนเบี่ยงเบนมาตรฐานเท่ากับ 1 เพื่อปรับปรุงประสิทธิภาพของ PCA และทำให้ทุกรายการข้อมูลมีมาตราส่วนใกล้เคียงกัน เพื่อป้องกันไม่ได้ตัวแปรที่มีค่าขนาดใหญ่มาครอบงำการวิเคราะห์ข้อมูล

* การคำนวณเมทริกซ์ความแปรปรวนร่วม (Covariance Matrix): เมทริกซ์ความแปรปรวนร่วมอธิบายความสัมพันธ์ระหว่างตัวแปรแต่ละคู่ในชุดข้อมูล

* การคำนวณค่า Eigenvalues และ Eigenvectors: เป็นขั้นตอนในการหาค่า Eigenvalues และ Eigenvectors ของเมทริกซ์ความแปรปรวนร่วม Eigenvector แสดงถึงทิศทางของความแปรปรวนสูงสุดในข้อมูล และ Eigenvalue จะระบุขนาดของความแปรปรวนในทิศทางของ Eigenvector แต่ละตัว

* การเลือกส่วนประกอบหลัก: Eigenvectors ได้รับการจัดอันดับตาม Eigenvalue ที่เกี่ยวข้องตามลำดับจากมากไปน้อย Eigenvector ที่มีค่า Eigenvalue สูงสุด (องค์ประกอบหลัก) หมายถึง องค์ประกอบ (component) ที่สามารถจับความแปรปรวนของข้อมูลหรืออธิบายข้อมูลได้มากที่สุด นักวิเคราะห์สามารถเลือกจำนวนองค์ประกอบหลักที่เพียงพอที่จะรักษาโครงสร้างของข้อมูลตามต้องการ

* การทำ projection ไปยังองค์ประกอบหลัก: จากนั้นข้อมูลต้นฉบับจะถูก project ลงบนองค์ประกอบหลักที่เลือก ซึ่งเป็นการแปลงข้อมูลให้เป็นระบบพิกัดใหม่ที่กำหนดโดยองค์ประกอบหลัก และชุดข้อมูลผลลัพธ์ที่ได้มีมิติลดลง

## Dataset: Breast Cancer dataset

ชุดข้อมูล Breast Cancer(มะเร็งเต้านม) เป็นข้อมูลชนิดเลขจำนวนจริงแบบหลายตัวแปรที่สามารถจำแนกประเภท (class) ได้ 2 แบบ ซึ่งเป็นการบ่งบอกว่าผู้ป่วยที่มีเนื้องอกว่าเป็นมะเร็งเต้านมหรือไม่ คือ malignant (ก้อนเนื้อที่มีความเสี่ยงต่อการเป็นมะเร็ง) และ benign (ก้อนเนื้อที่ไม่มีความเสี่ยงต่อการเป็นมะเร็ง)

ในชุดข้อมูล มีตัวอย่างที่ถูกระบุว่าเป็นประเภท malignant 212 รายการ และ อีก 357 รายการเป็นประเภท benign

มีจำนวนคุณลักษณะ (Features) ที่ใช้ในการจำแนก 30 คุณลักษณะ: radius, texture, perimeter, area, smoothness, fractal dimension, etc.

เราสามารถดาวน์โหลดชุดข้อมูลนี้ได้ [ที่นี่](https://archive.ics.uci.edu/ml/datasets/Breast+Cancer+Wisconsin+(Diagnostic)) หรือวิธีง่าย ๆ คือการโหลดชุดข้อมูลโดยใช้ไลบรารี sklearn

## Breast Cancer Data Exploration

เราจะใช้ โมดูล datasets ของ sklearn และนำเข้าชุดข้อมูลมะเร็งเต้านม ด้วยคำสั่ง:


```
from sklearn.datasets import load_breast_cancer
```
load_breast_cancer จะให้ทั้งป้ายกำกับ (labels) และข้อมูล หากต้องการดึงข้อมูล เราจะต้องเรียกด้วย .data และเรียกป้ายกำกับด้วย .target

ข้อมูลมีตัวอย่าง 569 รายการ ประกอบด้วยคุณลักษณะ 30 ตัว และแต่ละตัวอย่างมีป้ายกำกับที่เกี่ยวข้อง ชุดข้อมูลนี้มีป้ายกำกับ 2 แบบ คือ 0 (benign) และ 1 (malignant)
"""

from sklearn.datasets import load_breast_cancer
breast = load_breast_cancer()
breast_data = breast.data
breast_labels = breast.target

"""เราจะดูรูปร่าง (shape) ของตัวแปรที่เก็บข้อมูลและป้ายกำกับ"""

print(breast_data.shape)
print(breast_labels.shape)

"""ต่อไป เราจะนำเข้า numpy เพื่อปรับรูปร่างของ breast_labels ใหม่ ให้สามารถเชื่อมเข้ากับ breast_data เพื่อให้เราสามารถสร้าง DataFrame ที่มีทั้งข้อมูลและป้ายกำกับอยู่ด้วยกันได้"""

import numpy as np
labels = np.reshape(breast_labels,(569,1))
labels.shape

"""หลังจากปรับรูปร่างป้ายกำกับแล้ว คุณจะเชื่อมข้อมูลและป้ายกำกับเข้าด้วยกันตามแกนที่สอง ซึ่งหมายความว่ารูปร่างสุดท้ายของอาร์เรย์จะเป็น 569 x 31"""

final_breast_data = np.concatenate([breast_data,labels],axis=1)
final_breast_data.shape

"""จากนั้น เราจะนำเข้า pandas เพื่อสร้าง DataFrame ของข้อมูลสุดท้ายเพื่อแสดงข้อมูลในรูปแบบตาราง"""

import pandas as pd
breast_dataset = pd.DataFrame(final_breast_data)
breast_dataset.tail()

"""เมื่อเราทำการพิมพ์ชื่อคุณลักษณะที่มีอยู่ในชุดข้อมูลมะเร็งเต้านม จะเห็นว่าในอาร์เรย์ชื่อคุณลักษณะ ชื่อของช่องป้ายกำกับจะหายไป ดังนั้น เราจะต้องเพิ่มลงในอาร์เรย์ชื่อคุณลักษณะด้วยตนเอง เนื่องจากคุณจะต้องเอาอาร์เรย์นี้ไปกำหนดเป็นชื่อคอลัมน์ของ dataframe breast_dataset"""

features = breast.feature_names
features

features_labels = np.append(features,'label')
breast_dataset.columns = features_labels
breast_dataset.tail()
breast_data_slice = breast_dataset.iloc[:, [3,4,5,30]]

"""ลอง plot ความสัมพันธ์ของทุกคู่คุณลักษณะที่ slice ออกมา ด้วย pairplot() ที่อยู่ในไลบรารี seaborn"""

import seaborn as sns
sns.set()
p=sns.pairplot(breast_data_slice, hue = 'label')

"""เนื่องจากค่าของป้ายกำกับเดิมอยู่ในรูปแบบ 0,1 เราจะเปลี่ยนป้ายกำกับให้เป็น 'ฺBenign' และ 'Malignant' โดยใช้เมธอด .replace และใช้ inplace=True ซึ่งจะแก้ไข dataframe breast_dataset"""

breast_dataset['label'] = breast_dataset['label'].replace(0, 'Benign')
breast_dataset['label'] = breast_dataset['label'].replace(1, 'Malignant')
breast_dataset

"""## Data Visualization using PCA

จากที่กล่าวไว้ในตอนต้นว่า PCA สามารถเปลี่ยนข้อมูลมิติสูงให้เป็นองค์ประกอบหลักที่มีมิติต่ำ ดังนั้น จากนี้เราจะทดลองใช้ PCA เพื่อช่วยในการแสดงภาพข้อมูล (Visualization) ที่มีความซับซ้อนให้ชัดเจนและสามารถนำไปวิเคราะห์ได้ง่ายขึ้น

## Visualizing the Breast Cancer data

เราจะเริ่มต้นด้วยการทำ standardization เนื่องจากเอาต์พุตของ PCA จะขึ้นอยู่กับขนาดของค่าที่เก็บในแต่ละคุณลักษณะของข้อมูล

ถ้าต้องการใช้การทำ standardization ต้องนำเข้าโมดูล StandardScaler จากไลบรารี sklearn และเลือกเฉพาะคุณสมบัติ (features) จากชุดข้อมูล breast_dataset ที่สร้างในขั้นตอนการสำรวจข้อมูล แล้วทำการปรับขนาดโดยใช้ fit_transform กับข้อมูลคุณสมบัติ

ในขณะที่ใช้ StandardScaler คุณลักษณะแต่ละตัวของข้อมูลควรมีการแจกแจงแบบปกติ (Normal distribution) ซึ่งจะทำให้ขนาดของข้อมูลมีการแจกแจงที่มีค่าเฉลี่ย (Mean) เป็นศูนย์และค่าเบี่ยงเบนมาตรฐาน (SD) เท่ากับ 1
"""

from sklearn.preprocessing import StandardScaler
x = breast_dataset.loc[:, features].values
x = StandardScaler().fit_transform(x) # normalizing the features
x

"""ลองตรวจสอบว่าข้อมูลที่ทำค่าให้เป็นมาตรฐานมีค่าเฉลี่ยเป็นศูนย์และค่าเบี่ยงเบนมาตรฐานเป็น 1 หรือไม่ ด้วยคำสั่ง"""

np.mean(x),np.std(x)

#np.round(np.mean(x),2), np.round(np.std(x),2)

"""มาแปลงฟีเจอร์ที่ทำค่าให้เป็นมาตรฐานเป็นรูปแบบตารางด้วย DataFrame"""

feat_cols = ['feature'+str(i) for i in range(x.shape[1])]
normalised_breast = pd.DataFrame(x,columns=feat_cols)
normalised_breast.tail()

"""ส่วนต่อไปนี้ เราจะทำการ project ข้อมูลมะเร็งเต้านมที่มีสามสิบมิติไปยังองค์ประกอบหลัก (principal components) แบบสองมิติ

เราจะใช้ไลบรารี sklearn เพื่อนำเข้าโมดูล PCA และในฟังก์ชัน PCA เราจะส่งค่าจำนวนส่วนประกอบ คือ 2 (n_components=2) และสุดท้ายจะเรียก fit_transform กับข้อมูล
"""

from sklearn.decomposition import PCA
pca_breast = PCA(n_components=2) # n_components = จำนวน components
principalComponents_breast = pca_breast.fit_transform(x)
principalComponents_breast.shape

"""ต่อไป เรามาสร้าง DataFrame ที่จะมีค่าองค์ประกอบหลักสำหรับตัวอย่างทั้งหมด 569 รายการ"""

principal_breast_Df = pd.DataFrame(data = principalComponents_breast
             , columns = ['principal component 1', 'principal component 2'])
principal_breast_Df.tail()

# principal_breast_Df = pd.DataFrame(data = principalComponents_breast
#              , columns = ['principal component 1', 'principal component 2', 'principal component 3', 'principal component 4', 'principal component 5'])
# principal_breast_Df.tail()

"""เมื่อเราได้องค์ประกอบหลักแล้ว เราสามารถแสดงค่า explained_variance_ratio ซึ่งเป็นปริมาณสารสนเทศหรือความแปรปรวนที่แต่ละองค์ประกอบหลักสามารถอธิบายข้อมูลต้นฉบับ ดังนี้"""

print('Explained variation per principal component: {}'.format(pca_breast.explained_variance_ratio_))

"""จากผลลัพธ์ด้านบน เราจะสังเกตได้ว่าองค์ประกอบหลัก 1 สามารถอธิบายข้อมูลต้นฉบับได้ 44.2% ในขณะที่องค์ประกอบหลัก 2 อธิบายข้อมูลต้นฉบับได้เพียง 19%

แสดงว่า ถ้าเราใช้องค์ประกอบหลักเพียง 2 ตัว จะทำให้เราสามารถลดจำนวนมิติข้อมูลจาก 30 มิติ เหลือเพียง 2 มิติ ซึ่ง 2 องค์ประกอบหลักนี้สามารถอธิบายข้อมูลต้นฉบับได้ 63.2% ซึ่งหมายถึงข้อมูลต้นฉบับ 36.8% จะสูญหายไป

ต่อไปเราจะสร้างแผนภูมิเพื่อแสดงภาพของตัวอย่าง 569 รายการ ตาม องค์ประกอบหลัก 1 และองค์ประกอบหลัก ซึ่งแผนภูมิที่ได้ควรให้ข้อมูลเชิงลึกที่ดีเกี่ยวกับการกระจายของตัวอย่างทั้ง 2 ประเภท (benign และ malignant)
"""

import matplotlib.pyplot as plt

plt.figure()
plt.figure(figsize=(8,8))
plt.xticks(fontsize=10)
plt.yticks(fontsize=12)
plt.xlabel('Principal Component - 1',fontsize=18)
plt.ylabel('Principal Component - 2',fontsize=18)
plt.title("Principal Component Analysis\nof Breast Cancer Dataset",fontsize=20)
targets = ['Benign', 'Malignant']
colors = ['g', 'r']
for target, color in zip(targets,colors):
    indicesToKeep = breast_dataset['label'] == target
    plt.scatter(principal_breast_Df.loc[indicesToKeep, 'principal component 1']
               , principal_breast_Df.loc[indicesToKeep, 'principal component 2'], c = color, s = 50)

plt.legend(targets,prop={'size': 15})