# -*- coding: utf-8 -*-
"""Nattapong Panthiya - DataMiningLab_04_K-Means Clustering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13i4P89sQfKtTiv72VQG0iG5kD2Ymjtwn

# K-Means Clustering
เป็นวิธีการเรียนรู้แบบไม่มีผู้สอน ใช้สำหรับจัดกลุ่มจุดข้อมูล โดยอัลกอริทึมจะแบ่งจุดข้อมูล ออกเป็น K คลัสเตอร์ ซึ่งสมาชิกของคลัสเตอร์จะอยู่ใกล้กับจุดศูนย์กลาง (Centroid) ของคลัสเตอร์นั้นมากที่สุด

การจัดกลุ่มแบบ K-mean เราต้องกำหนดค่า K ซึ่งเป็นจำนวนคลัสเตอร์ที่เราต้องการจัดกลุ่ม วิธีการในการหาค่า K ที่เหมาะสม คือ
[Elbow method](https://lengyi.medium.com/%E0%B8%AB%E0%B8%B2%E0%B8%88%E0%B8%B3%E0%B8%99%E0%B8%A7%E0%B8%99-clusters-%E0%B8%97%E0%B8%B5%E0%B9%88%E0%B9%80%E0%B8%AB%E0%B8%A1%E0%B8%B2%E0%B8%B0%E0%B8%AA%E0%B8%A1%E0%B8%AA%E0%B8%B3%E0%B8%AB%E0%B8%A3%E0%B8%B1%E0%B8%9A-kmeans-clustering-%E0%B8%94%E0%B9%89%E0%B8%A7%E0%B8%A2-elbow-method-85421efe9d#:~:text=Elbow%20method%20%E0%B8%84%E0%B8%B7%E0%B8%AD%E0%B8%A7%E0%B8%B4%E0%B8%98%E0%B8%B5%E0%B8%81%E0%B8%B2%E0%B8%A3,%2Dof%2DSquares%20(WCSS))  

วิธีนี้ทำให้เราสามารถสร้างกราฟ และหาจุดที่เหมาะสมของจำนวน Clusters ซึ่งก็คือจุดที่กราฟมีลักษณะ “หัก” ที่สุดนั่นเอง

## Example

เราจะทำการจัดกลุ่มจุดข้อมูลจำนวน 10 จุด ที่ประกอบไปด้วยแอตทริบิวต์ x และ y ดังตาราง

| point 	| x  	| y  	|
|-------|----|----|
| p1    	| 4  	| 21 	|
| p2    	| 5  	| 19 	|
| p3    	| 10 	| 24 	|
| p4    	| 4  	| 17 	|
| p5    	| 3  	| 16 	|
| p6    	| 11 	| 25 	|
| p7    	| 14 	| 24 	|
| p8    	| 6  	| 22 	|
| p9    	| 10 	| 21 	|
| p10   	| 12 	| 21 	|

เริ่มด้วยการลอง plot จุดข้อมูลเพื่อให้เห็นภาพก่อน โดยการเรียกใช้ scatter() ใน matplotlib
"""

import matplotlib.pyplot as plt

x = [4, 5, 10, 4, 3, 11, 14 , 6, 10, 12]
y = [21, 19, 24, 17, 16, 25, 24, 22, 21, 21]

plt.scatter(x, y)
plt.show()

"""ทำการวนซ้ำเพื่อจัดกลุ่มจุดข้อมูลด้วยวิธีการ K-means โดยแต่ละรอบจะทำการเปลี่ยนค่า K ไปเรื่อย ๆ(เนื่องจากในตัวอย่างมีจุดข้อมูลทั้งหมด 10 จุด ดังนั้น จะทำการเปลี่ยนค่า K ตั้งแต่ 1 ถึง 10 คลัสเตอร์) เพื่อคำนวณหาค่า  Within-Cluster-Sum-of-Squares (WCSS) และนำมาวาดกราฟ เพื่อหาจุดหักของกราฟ และกำหนดให้เป็นจำนวนคลัสเตอร์ หรือค่า K ที่เหมาะสมที่สุดของชุดข้อมูล

ในการใช้งานอัลกอริทึม K-means จำเป็นต้อง import ไลบรารีย่อย KMeans ดังนี้

```
from sklearn.cluster import KMeans
```

เราใช้ Elbow Method เพื่อแสดงกราฟของค่า WCSS สำหรับค่า K ตั้งแต่ 1 ถึง 10 ได้ตามตัวอย่าง code:

"""

from sklearn.cluster import KMeans

data = list(zip(x, y))
print(data)
wcss = []

for i in range(1,11):
    kmeans = KMeans(n_clusters=i,init='k-means++', n_init='auto')
    kmeans.fit(data)
    wcss.append(kmeans.inertia_)

plt.plot(range(1,11), wcss, marker='o')
plt.title('Elbow method')
plt.xlabel('Number of clusters (K)')
plt.ylabel('WCSS')
plt.show()

"""จากกราฟจะเห็นว่าจุดหักของกราฟอยู่ที่ตำแหน่งค่า K = 2 ดังนั้น เราสามารถสรุปจำนวนคลัสเตอร์ที่เหมาะสมในการแบ่งจุดข้อมูลตัวอย่างของเรา คือ แบ่งเป็น **2 คลัสเตอร์**

เมื่อเราได้จำนวนคลัสเตอร์ที่เหมาะสมแล้ว เราจะทำการสร้างออปเจ็กการจัดกลุ่มแบบ K-Means โดยใช้ KMeans() อีกครั้ง โดยครั้งนี้ เราจะกำหนดค่าพารามิเตอร์ n_clusters = 2 และทำการจัดกลุ่มโดยให้ออปเจ็กเรียกใช้เมธอด fit() และทำการแสดงผลลัพธ์การจัดกลุ่มเป็น Scatter plot
"""

kmeans = KMeans(n_clusters=2)
kmeans.fit(data)

plt.scatter(x, y, c=kmeans.labels_)
plt.show()

"""# แบบฝึกหัด

ให้ลองจัดกลุ่มข้อมูลต่อไปนี้ ด้วยวิธี K-Means Clustering โดยให้แสดง
1. วิธีการเลือกค่า K ที่เหมาะสมด้วย Elbow Method (วาดกราฟด้วย)
2. ผลลัพธ์การจัดกลุ่มแบบ Scatter plot บนแกน 2 มิติ

| point 	| x  	| y  	|
|-------|----|----|
| p1    	| 4  	| 21 	|
| p2    	| 5  	| 19 	|
| p3    	| 10 	| 24 	|
| p4    	| 4  	| 17 	|
| p5    	| 9  	| 13 	|
| p6    	| 11 	| 15 	|
| p7    	| 14 	| 24 	|
| p8    	| 6  	| 22 	|
| p9    	| 10 	| 21 	|
| p10   	| 12 	| 21 	|
| p11    	| 8 	| 14 	|
| p12    	| 3 	| 16 	|
| p13    	| 11	| 25 	|
| p14    	| 10 	| 15 	|
| p15   	| 9 	| 10 	|
"""

# ให้เขียน code ของแบบฝึกหัดที่นี่
x = [4, 5, 10, 4, 9, 11, 14, 6, 10, 12, 8, 3, 11, 10, 9]
y = [21, 19, 24, 17, 13, 15, 24, 22, 21, 21, 14, 16, 25, 15, 10 ]
data2 = list(zip(x, y))
print(data2)
wcss = []

for i in range(1,15):
    kmeans = KMeans(n_clusters=i,init='k-means++', n_init='auto')
    kmeans.fit(data2)
    wcss.append(kmeans.inertia_)

plt.plot(range(1,15), wcss, marker='o')
plt.title('Elbow method')
plt.xlabel('Number of clusters (K)')
plt.ylabel('WCSS')
plt.show()
print()
print("ผลลัพธ์ของการจัดกลุ่ม")
kmeans = KMeans(n_clusters=3)
kmeans.fit(data2)

plt.scatter(x, y, c=kmeans.labels_)
plt.show()